module.exports = [
  // Sudden Braking Zones
  {
    type: 'sudden_brake',
    lat: 13.0123,
    lng: 80.2121,
    severity: 5,
    description: 'Severe sudden braking zone at Kathipara Junction during evening rush due to converging flyover traffic from 3 directions. Vehicles descending the flyover frequently brake hard when merging.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Kathipara Junction',
    landmark: 'Kathipara Flyover',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0628,
    lng: 80.2552,
    severity: 4,
    description: 'Sudden braking near Gemini Circle at 6 PM due to merging traffic from Anna Salai and Cathedral Road. Signal changes cause chain-reaction braking.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Anna Salai',
    landmark: 'Gemini Circle',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 12.9012,
    lng: 80.2279,
    severity: 4,
    description: 'Sudden braking near Sholinganallur signal during rains. Water logging causes vehicles to brake abruptly. Visibility reduced in heavy rain.',
    timeOfDay: 'morning_rush',
    weather: 'rain',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Sholinganallur Signal',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0475,
    lng: 80.2396,
    severity: 3,
    description: 'Sudden braking at Teynampet signal as pedestrians cross during green signal. Auto-rickshaws stop abruptly to pick passengers.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Anna Salai',
    landmark: 'Teynampet Junction',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0827,
    lng: 80.2707,
    severity: 4,
    description: 'Sudden braking at Chennai Central approach road. High bus and auto traffic causes erratic stopping. Especially dangerous during morning rush.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Poonamallee High Road',
    landmark: 'Chennai Central Railway Station',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0475,
    lng: 80.234,
    severity: 3,
    description: 'Frequent chain-braking near Panagal Park due to MTC buses stopping without warning at unmarked bus stops.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'South Usman Road',
    landmark: 'Panagal Park',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0043,
    lng: 80.2575,
    severity: 4,
    description: 'Abrupt braking on Adyar Bridge approach. Narrow lanes and merging traffic from Lattice Bridge Road cause sudden stops.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Sardar Patel Road',
    landmark: 'Adyar Bridge',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0604,
    lng: 80.2185,
    severity: 3,
    description: 'Braking zone near Vadapalani signal. Temple visitors jaywalking and heavy auto-rickshaw traffic cause abrupt stops.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Arcot Road',
    landmark: 'Vadapalani Temple',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 12.9249,
    lng: 80.1445,
    severity: 4,
    description: 'Sharp braking at Tambaram level crossing when railway gates close without sufficient warning. Long queues form quickly.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Tambaram Railway Crossing',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 12.9907,
    lng: 80.2329,
    severity: 3,
    description: 'Sudden braking near Guindy Industrial Estate entrance due to trucks making slow turns into factory gates.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Mount Poonamallee Road',
    landmark: 'Guindy Industrial Estate',
    verified: true
  },

  // Blind Turns
  {
    type: 'blind_turn',
    lat: 12.8256,
    lng: 80.2463,
    severity: 4,
    description: 'Dangerous blind turn on ECR near Muttukadu. Overgrown vegetation blocks line of sight. Multiple near-miss incidents reported on weekends.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Muttukadu Boat House',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.0627,
    lng: 80.2707,
    severity: 5,
    description: 'Blind turn on Mount Road near LIC building. Tall compound wall blocks visibility completely. Two-wheelers cutting across lanes at high speed.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Anna Salai (Mount Road)',
    landmark: 'LIC Building',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.0447,
    lng: 80.2647,
    severity: 4,
    description: 'Blind curve on Dr. Radhakrishnan Salai near the lighthouse. Parked cars reduce visibility. Cyclists and pedestrians appear unexpectedly around the bend.',
    timeOfDay: 'morning_rush',
    weather: 'fog',
    roadName: 'Dr. Radhakrishnan Salai',
    landmark: 'Chennai Lighthouse',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.0336,
    lng: 80.2497,
    severity: 3,
    description: 'Sharp blind turn at the Alwarpet Canal Bridge. Narrow road width and parked vehicles create dangerous blind spot.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'C.P. Ramaswamy Road',
    landmark: 'Alwarpet Canal Bridge',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.0858,
    lng: 80.2154,
    severity: 4,
    description: 'Blind turn at Anna Nagar 2nd Avenue and 18th Main Road intersection. Large banyan tree completely blocks left-turn visibility.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: '2nd Avenue, Anna Nagar',
    landmark: 'Anna Nagar Tower Park',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.0471,
    lng: 80.1927,
    severity: 3,
    description: 'Hidden curve on Porur bypass road behind a construction barricade. Unmarked and poorly lit at night.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Porur Bypass Road',
    landmark: 'Porur Junction',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.1098,
    lng: 80.2396,
    severity: 3,
    description: 'Blind entry from L&T service road merging onto Poonamallee High Road. No mirror or warning signs installed.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Poonamallee High Road',
    landmark: 'L&T Flyover',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 12.9735,
    lng: 80.2609,
    severity: 4,
    description: 'Dangerous S-curve near Thiruvanmiyur MRTS station. Vehicles exiting the parking lot are invisible to through traffic.',
    timeOfDay: 'evening_rush',
    weather: 'rain',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Thiruvanmiyur MRTS Station',
    verified: true
  },

  // Habitual Violations
  {
    type: 'habitual_violation',
    lat: 13.0654,
    lng: 80.2628,
    severity: 3,
    description: 'Chronic jaywalking near Spencer Plaza. Pedestrians cross Anna Salai at all points ignoring the foot overbridge. Extremely dangerous during peak hours.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Anna Salai',
    landmark: 'Spencer Plaza',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0569,
    lng: 80.2775,
    severity: 4,
    description: 'Consistent wrong-way driving on Marina Beach Road one-way during early morning hours. Two-wheelers and autos frequently violate.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Kamarajar Salai',
    landmark: 'Marina Beach Promenade',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0417,
    lng: 80.2341,
    severity: 3,
    description: 'Red-light running at T. Nagar Pondy Bazaar junction. Two-wheelers routinely jump signal, especially during late evening hours.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Pondy Bazaar',
    landmark: 'T. Nagar Bus Terminus',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0095,
    lng: 80.2224,
    severity: 4,
    description: 'Illegal U-turns at Guindy National Park entrance. Vehicles from Kathipara side make unsafe U-turns despite "No U-turn" sign.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Sardar Patel Road',
    landmark: 'Guindy National Park',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0743,
    lng: 80.2089,
    severity: 2,
    description: 'Habitual triple-riding on two-wheelers near Koyambedu Bus Terminus. Families with children riding without helmets.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Jawaharlal Nehru Road',
    landmark: 'Koyambedu Bus Terminus',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0601,
    lng: 80.2489,
    severity: 3,
    description: 'Persistent footpath parking on Nungambakkam High Road forces pedestrians to walk on the main road into traffic.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Nungambakkam High Road',
    landmark: 'Nungambakkam Railway Station',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0868,
    lng: 80.2573,
    severity: 4,
    description: 'Dangerous overloaded share-autos near Flower Bazaar. Vehicles carry 12+ passengers and drive erratically through congested streets.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'NSC Bose Road',
    landmark: 'Flower Bazaar',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 12.9485,
    lng: 80.2204,
    severity: 3,
    description: 'Chronic wrong-side driving on Velachery Main Road near Phoenix Mall. Two-wheelers use opposite lane to avoid traffic.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Velachery Main Road',
    landmark: 'Phoenix MarketCity',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0734,
    lng: 80.2428,
    severity: 3,
    description: 'Bus lane violations on Anna Salai near Egmore. Cars and autos use dedicated bus lane, causing MTC buses to brake suddenly.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Anna Salai',
    landmark: 'Egmore Museum',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.0472,
    lng: 80.2504,
    severity: 3,
    description: 'Sudden braking at Thousand Lights intersection due to auto-rickshaws cutting across from the mosque side.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Anna Salai',
    landmark: 'Thousand Lights Mosque',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 12.869,
    lng: 80.227,
    severity: 3,
    description: 'Obscured turn on Kelambakkam Road. Construction debris narrows the road and blocks view around the bend.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Kelambakkam Road',
    landmark: 'Near SRM University',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.0476,
    lng: 80.2093,
    severity: 4,
    description: 'Speed limit violations on inner ring road near Ashok Nagar. Vehicles routinely exceed 80 km/h in a 40 km/h zone.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Inner Ring Road',
    landmark: 'Ashok Nagar',
    verified: true
  },

  // Accident-Prone Hotspots
  {
    type: 'accident',
    lat: 13.011,
    lng: 80.2121,
    severity: 5,
    description: 'High-severity crash-risk zone: Kathipara to GST Road stretch. Flyover exit speed combined with heavy merges can cause rear-end and side-impact crashes, especially during peak hours.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'GST Road (NH 45)',
    landmark: 'Kathipara Junction Flyover Exit',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.086,
    lng: 80.1642,
    severity: 5,
    description: 'Crash-risk hotspot at Maduravoyal interchange. High-speed bypass traffic merging with slower local traffic creates frequent conflict points, especially at night.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Chennai Bypass Road',
    landmark: 'Maduravoyal Interchange',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.072,
    lng: 80.2089,
    severity: 4,
    description: 'Accident-prone zone at Koyambedu flyover exit. Buses and heavy vehicles descending the flyover at speed cause frequent collisions with slower local traffic.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Poonamallee High Road',
    landmark: 'Koyambedu Flyover',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.0613,
    lng: 80.2758,
    severity: 4,
    description: 'Pedestrian conflict zone near Anna Arch/War Memorial. Visitors and joggers cross outside designated crossings, increasing sudden-braking and collision risk.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Kamarajar Salai',
    landmark: 'Anna Arch / War Memorial',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.0878,
    lng: 80.2784,
    severity: 4,
    description: 'High-risk crash zone at Napier Bridge approach. Vehicles accelerate on the wide stretch and lose control at the bridge curve, especially during rain.',
    timeOfDay: 'evening_rush',
    weather: 'rain',
    roadName: 'Napier Bridge',
    landmark: 'Fort St. George',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.986,
    lng: 80.216,
    severity: 5,
    description: 'Crash-risk corridor near Nanganallur on Inner Ring Road. Higher speeds combined with low visibility at night increase rear-end and loss-of-control risk.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Inner Ring Road',
    landmark: 'Nanganallur Junction',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.978,
    lng: 80.21,
    severity: 4,
    description: 'Multiple rear-end collision zone on Inner Ring Road near Adambakkam. Unlit median openings cause head-on crashes with vehicles making illegal U-turns.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Inner Ring Road',
    landmark: 'Adambakkam',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.94,
    lng: 80.2204,
    severity: 5,
    description: 'Velachery Bypass crash-risk hotspot. High-speed trucks and buses meet unprotected intersections and two-wheelers weaving through traffic.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Velachery Bypass Road',
    landmark: 'Velachery Bypass Junction',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.942,
    lng: 80.172,
    severity: 4,
    description: 'Velachery-Tambaram (SH48) accident zone. Frequent side-impact crashes at uncontrolled intersections. Heavy mix of local and highway traffic.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Velachery-Tambaram Road (SH48)',
    landmark: 'Perungudi Bus Stop',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.96,
    lng: 80.188,
    severity: 4,
    description: 'Pallavaram-Thoraipakkam Road (SH109) crash hotspot. Construction zones narrow lanes unpredictably, causing sideswipe crashes and rear-end collisions.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Pallavaram-Thoraipakkam Road (SH109)',
    landmark: 'Pallavaram Junction',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.129,
    lng: 80.303,
    severity: 4,
    description: 'Chennai-Ennore Expressway fatal stretch. High-speed lorries and tankers cause catastrophic crashes. Poor lighting and no emergency shoulders.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Chennai-Ennore Expressway',
    landmark: 'Ennore Port Road',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.987,
    lng: 80.242,
    severity: 3,
    description: 'Taramani Link Road crash-risk zone. Unsafe median openings and heavy IT corridor traffic create frequent T-bone conflict points.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Taramani Link Road',
    landmark: 'TIDEL Park',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.08,
    lng: 80.267,
    severity: 4,
    description: 'Chennai Central Metro station pedestrian conflict zone. Commuters rushing to catch trains cross the road unpredictably near station exits and bus stops.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'EVR Periyar Salai',
    landmark: 'Chennai Central Metro Station',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.088,
    lng: 80.2815,
    severity: 3,
    description: 'Broadway Bus Terminus area - high pedestrian-vehicle conflict zone. Overcrowded bus stops push pedestrians into traffic lanes. Multiple minor injuries monthly.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'NSC Bose Road',
    landmark: 'Broadway Bus Terminus',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.067,
    lng: 80.246,
    severity: 3,
    description: 'Nehru Park Metro Station area. Two-wheeler riders weaving through heavy traffic near metro construction barriers cause frequent collisions.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Pantheon Road',
    landmark: 'Nehru Park Metro Station',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.895,
    lng: 80.2279,
    severity: 5,
    description: 'OMR Sholinganallur IT corridor crash-risk stretch. High-speed traffic, waterlogging during rains, and poor street lighting increase severe collision likelihood.',
    timeOfDay: 'night',
    weather: 'rain',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Sholinganallur Junction',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.85,
    lng: 80.235,
    severity: 4,
    description: 'OMR Kelambakkam stretch - frequent head-on collisions due to illegal median cuts and high truck traffic from Chengalpet.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Kelambakkam Junction',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.05,
    lng: 80.25,
    severity: 4,
    description: 'Thousand Lights flyover exit crash-risk zone. Vehicles descend at high speed and encounter slow traffic near the Anna Salai signal.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Anna Salai',
    landmark: 'Thousand Lights Flyover',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.037,
    lng: 80.262,
    severity: 3,
    description: 'Mylapore tank area - frequent two-wheeler skid accidents on wet roads during monsoon. Temple traffic adds to congestion and collision risk.',
    timeOfDay: 'afternoon',
    weather: 'rain',
    roadName: 'Kutchery Road',
    landmark: 'Kapaleeshwarar Temple',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.9516,
    lng: 80.1462,
    severity: 4,
    description: 'Chromepet railway crossing crash-risk zone. Vehicles sometimes attempt to cross late as gates begin closing, creating severe conflict.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Chromepet Railway Crossing',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.9675,
    lng: 80.1491,
    severity: 4,
    description: 'Pallavaram flyover descent crash zone. Steep gradient causes heavy vehicles to lose braking control. Multiple truck-car collisions reported.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Pallavaram Flyover',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.11,
    lng: 80.23,
    severity: 4,
    description: 'Perambur corridor crash-risk zone. Narrow roads with high bus frequency and limited pedestrian space create frequent near-misses and collisions.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Perambur High Road',
    landmark: 'Perambur Railway Station',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.053,
    lng: 80.253,
    severity: 3,
    description: 'Royapettah High Road crash zone near hospital. Ambulances and patient vehicles making sudden turns cause chain-reaction accidents.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Royapettah High Road',
    landmark: 'Royapettah Government Hospital',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.084,
    lng: 80.242,
    severity: 3,
    description: 'Kilpauk Garden Road junction - signal timing and turning conflicts increase T-bone risk, especially during peak hours.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Kilpauk Garden Road',
    landmark: 'Kilpauk Medical College',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.9835,
    lng: 80.264,
    severity: 4,
    description: 'Thiruvanmiyur ECR junction crash-risk zone. High-speed ECR traffic meets dense local traffic with complex turning movements.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'East Coast Road / OMR Junction',
    landmark: 'Thiruvanmiyur Junction',
    verified: true
  },

  // Tiruvallur Region
  {
    type: 'sudden_brake',
    lat: 13.1435,
    lng: 79.9064,
    severity: 3,
    description: 'Sudden braking at Tiruvallur Bus Stand entrance. MTC and private buses stop abruptly without pulling into the bay. Congested approach causes chain braking.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Tiruvallur High Road',
    landmark: 'Tiruvallur Bus Stand',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.151,
    lng: 79.912,
    severity: 3,
    description: 'Blind curve near Tiruvallur Railway Station underpass. Low clearance and poor lighting make oncoming vehicles invisible until the last moment.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Station Road',
    landmark: 'Tiruvallur Railway Underpass',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.138,
    lng: 79.918,
    severity: 2,
    description: 'Wrong-side driving on Tiruvallur-Poonamallee Road shoulder. Two-wheelers and autos use the wrong side to avoid traffic near the temple zone.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Tiruvallur-Poonamallee Road',
    landmark: 'Veeraraghava Perumal Temple',
    verified: true
  },

  // Avadi Region
  {
    type: 'accident',
    lat: 13.1146,
    lng: 80.101,
    severity: 4,
    description: 'Avadi-Poonamallee corridor crash-risk hotspot. Heavy industrial vehicles mixing with two-wheelers increases rear-end and sideswipe risk at peak times.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Avadi-Poonamallee Highway',
    landmark: 'Avadi HVF Gate',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.121,
    lng: 80.1025,
    severity: 4,
    description: 'Sudden braking near Avadi Bus Depot. Buses exiting the depot cut across traffic lanes without signalling, causing rear-end collisions.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'CTH Road',
    landmark: 'Avadi Bus Depot',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.108,
    lng: 80.095,
    severity: 3,
    description: 'Red-light jumping at Avadi Toll Gate junction. Vehicles from all directions routinely ignore the signal, especially during non-peak hours.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Chennai-Bangalore Highway (NH4)',
    landmark: 'Avadi Toll Gate',
    verified: true
  },

  // Arakkonam Region
  {
    type: 'accident',
    lat: 13.083,
    lng: 79.67,
    severity: 4,
    description: 'Arakkonam-Kanchipuram Road crash-risk stretch. Narrow undivided road with heavy truck traffic and risky overtakes increases severe collision likelihood.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Arakkonam-Kanchipuram Road',
    landmark: 'Arakkonam Railway Junction',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 13.076,
    lng: 79.663,
    severity: 3,
    description: 'Blind curve near Arakkonam Air Force Station approach road. High walls on both sides block all visibility. No convex mirror installed.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'IAF Station Road',
    landmark: 'Arakkonam Air Force Station',
    verified: true
  },

  // Sriperumbudur Region
  {
    type: 'accident',
    lat: 12.971,
    lng: 79.941,
    severity: 5,
    description: 'Sriperumbudur Highway crash-risk stretch. High-speed highway traffic meets unmarked speed breakers and factory entrances, increasing sudden-braking and rear-end risk.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Chennai-Bangalore Highway (NH4)',
    landmark: 'Sriperumbudur Toll Plaza',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 12.965,
    lng: 79.948,
    severity: 4,
    description: 'Sudden braking at Sriperumbudur SIPCOT gate. Industrial trucks make abrupt turns into factory entrances without warning. Frequent rear-end crashes.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'NH4 Service Road',
    landmark: 'SIPCOT Industrial Park',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 12.978,
    lng: 79.935,
    severity: 3,
    description: 'Illegal U-turns on NH4 near Sriperumbudur temple. Pilgrims and local traffic make dangerous U-turns across the highway median.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Chennai-Bangalore Highway (NH4)',
    landmark: 'Sriperumbudur Ramanuja Temple',
    verified: true
  },

  // Kanchipuram Region
  {
    type: 'accident',
    lat: 12.8342,
    lng: 79.7036,
    severity: 5,
    description: 'Kanchipuram-Chennai road crash-risk hotspot. Tourist buses and cargo vehicles mix with local traffic, with sudden stops near junctions and markets.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Kanchipuram-Chennai Road (NH4)',
    landmark: 'Kanchipuram Bus Terminal',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 12.841,
    lng: 79.71,
    severity: 3,
    description: 'Chronic jaywalking near Kanchipuram Kamakshi Temple. Pilgrims cross the busy main road from all directions, ignoring pedestrian crossings.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'East Raja Street',
    landmark: 'Kamakshi Amman Temple',
    verified: true
  },
  {
    type: 'blind_turn',
    lat: 12.828,
    lng: 79.698,
    severity: 4,
    description: 'Dangerous blind turn near Kanchipuram Silk Market area. Narrow streets with parked silk cargo vehicles obstruct visibility around corners.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Pillai Kattalai Street',
    landmark: 'Kanchipuram Silk Market',
    verified: true
  },

  // Kundrathur Region
  {
    type: 'sudden_brake',
    lat: 12.999,
    lng: 80.099,
    severity: 3,
    description: 'Sudden braking near Kundrathur Junction. Auto-rickshaws and share vans stop unpredictably to pick up passengers along GST Road.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Kundrathur Junction',
    verified: true
  },
  {
    type: 'accident',
    lat: 13.007,
    lng: 80.105,
    severity: 4,
    description: 'Kundrathur-Porur Road crash-risk zone. Narrow two-lane road with heavy lorry traffic and risky overtakes increases head-on collision risk.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Kundrathur-Porur Road',
    landmark: 'Kundrathur Bridge',
    verified: true
  },

  // Thakkolam Region
  {
    type: 'accident',
    lat: 13.059,
    lng: 79.725,
    severity: 3,
    description: 'Thakkolam Railway Crossing accident-prone zone. No barricade warning system. Vehicles attempt to cross during approaching trains.',
    timeOfDay: 'morning_rush',
    weather: 'fog',
    roadName: 'Thakkolam-Arakkonam Road',
    landmark: 'Thakkolam Railway Crossing',
    verified: true
  },
  {
    type: 'habitual_violation',
    lat: 13.054,
    lng: 79.732,
    severity: 2,
    description: 'No-helmet riding endemic on Thakkolam inner roads. Two-wheeler riders routinely flout helmet rules in the semi-rural stretch.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Thakkolam Main Road',
    landmark: 'Thakkolam Town Center',
    verified: true
  },

  // Walajabad Region
  {
    type: 'accident',
    lat: 12.787,
    lng: 79.718,
    severity: 4,
    description: 'Walajabad Highway junction crash zone. NH-level traffic speed on a single-lane road. Head-on collisions frequent during overtaking maneuvers.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Walajabad-Kanchipuram Road',
    landmark: 'Walajabad Bus Stand',
    verified: true
  },

  // Vandalur Region
  {
    type: 'sudden_brake',
    lat: 12.888,
    lng: 80.081,
    severity: 3,
    description: 'Sudden braking near Vandalur Zoo entrance. Tourist vehicles and school buses make abrupt stops to drop passengers on the highway.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Arignar Anna Zoological Park (Vandalur Zoo)',
    verified: true
  },
  {
    type: 'accident',
    lat: 12.875,
    lng: 80.085,
    severity: 4,
    description: 'Vandalur-Kelambakkam Road crash-risk hotspot. Two-lane road with limited lighting and heavy truck traffic increases head-on and sideswipe risk at night.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Vandalur-Kelambakkam Road',
    landmark: 'SRM University Entrance',
    verified: true
  },

  // Poonamallee Region
  {
    type: 'accident',
    lat: 13.047,
    lng: 80.103,
    severity: 4,
    description: 'Poonamallee Bypass junction crash-risk zone. Vehicles exiting the bypass at speed encounter slower local traffic and frequent lane changes.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Chennai Bypass Road',
    landmark: 'Poonamallee Bypass Junction',
    verified: true
  },
  {
    type: 'sudden_brake',
    lat: 13.042,
    lng: 80.112,
    severity: 3,
    description: 'Hard braking near Poonamallee Military compound. Army vehicle convoys enter/exit causing civilian traffic to brake suddenly on the narrow road.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'Poonamallee High Road',
    landmark: 'Poonamallee Cantonment',
    verified: true
  },

  // South and Coastal Chennai
  {
    type: 'sudden_brake',
    lat: 12.9958,
    lng: 80.2599,
    severity: 4,
    description: 'Frequent hard braking on LB Road due to buses pulling out abruptly and pedestrians crossing between vehicles.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'LB Road',
    landmark: 'Adyar (Depot area)',
    verified: false
  },
  {
    type: 'habitual_violation',
    lat: 12.9898,
    lng: 80.2558,
    severity: 3,
    description: 'Wrong-side riding on service lanes to bypass congestion; two-wheelers commonly cut against traffic near the signal.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Thiruvanmiyur Signal',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.9726,
    lng: 80.2703,
    severity: 3,
    description: 'Blind left-turn into a narrow lane with parked cars blocking visibility; two-wheelers appear suddenly around the corner.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Besant Nagar Beach Road',
    landmark: 'Besant Nagar',
    verified: false
  },
  {
    type: 'sudden_brake',
    lat: 12.9556,
    lng: 80.2696,
    severity: 3,
    description: 'Sudden braking near beach access as cars slow unexpectedly to park; pedestrians cross without looking.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'ECR Service Road',
    landmark: 'Neelankarai',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.9358,
    lng: 80.2709,
    severity: 4,
    description: 'Hidden curve with roadside stalls narrowing the lane; oncoming traffic becomes visible late, especially at dusk.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Palavakkam',
    verified: false
  },
  {
    type: 'habitual_violation',
    lat: 12.9256,
    lng: 80.2688,
    severity: 3,
    description: 'Persistent illegal U-turns at a median opening; vehicles stop suddenly in the fast lane to turn.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Kottivakkam',
    verified: false
  },
  {
    type: 'sudden_brake',
    lat: 12.9108,
    lng: 80.2652,
    severity: 4,
    description: 'Hard braking in a school zone where autos stop abruptly to pick up students; congestion peaks on weekdays.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'ECR Service Road',
    landmark: 'Injambakkam',
    verified: false
  },
  {
    type: 'accident',
    lat: 12.8988,
    lng: 80.2638,
    severity: 4,
    description: 'Crash-risk point near a junction: fast through-traffic meets turning vehicles and buses changing lanes late.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Akkarai',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.9153,
    lng: 80.2562,
    severity: 3,
    description: 'Blind merge from a side street onto ECR with limited line of sight; braking distance worsens during rain.',
    timeOfDay: 'night',
    weather: 'rain',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Near Neelankarai Junction',
    verified: false
  },
  {
    type: 'habitual_violation',
    lat: 12.9047,
    lng: 80.2521,
    severity: 2,
    description: 'High-speed weaving by two-wheelers on the ECR stretch; risky overtakes and shoulder riding are common at night.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'East Coast Road (ECR)',
    landmark: 'Near Akkarai Bridge',
    verified: false
  },

  // OMR corridor
  {
    type: 'sudden_brake',
    lat: 12.9723,
    lng: 80.2436,
    severity: 4,
    description: 'Abrupt braking near IT corridor merge as cars cut across lanes to take the service road exit.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Perungudi',
    verified: false
  },
  {
    type: 'habitual_violation',
    lat: 12.9599,
    lng: 80.2449,
    severity: 3,
    description: 'Two-wheelers routinely ride against flow on the service lane to bypass signal queues.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'OMR Service Road',
    landmark: 'Thoraipakkam',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.9466,
    lng: 80.2465,
    severity: 3,
    description: 'Blind entry from a parking/service lane onto main road; cars accelerate into traffic with minimal gap checks.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Karapakkam',
    verified: false
  },
  {
    type: 'accident',
    lat: 12.9186,
    lng: 80.2277,
    severity: 4,
    description: 'Crash-risk junction with heavy turning movements and late lane changes around a large signal.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Perumbakkam Link Road Junction',
    verified: false
  },
  {
    type: 'sudden_brake',
    lat: 12.909,
    lng: 80.2077,
    severity: 3,
    description: 'Stop-and-go braking near Navalur as vehicles slow suddenly for speed breakers and unmarked crossings.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'OMR / Navalur Road',
    landmark: 'Navalur',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.8605,
    lng: 80.2012,
    severity: 4,
    description: 'Poorly lit curve near Siruseri where vehicles enter/exit campuses; visibility drops sharply during rain.',
    timeOfDay: 'night',
    weather: 'rain',
    roadName: 'Rajiv Gandhi Salai (OMR)',
    landmark: 'Siruseri SIPCOT',
    verified: false
  },

  // Tambaram / Chromepet / Pallavaram belt
  {
    type: 'sudden_brake',
    lat: 12.9345,
    lng: 80.1372,
    severity: 4,
    description: 'Frequent sudden braking near bus stop and shopfronts; vehicles stop abruptly and two-wheelers cut in.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Chromepet Bus Stop',
    verified: false
  },
  {
    type: 'habitual_violation',
    lat: 12.9692,
    lng: 80.1508,
    severity: 3,
    description: 'Lane-cutting and signal violations at a busy junction; two-wheelers squeeze through at the signal change.',
    timeOfDay: 'morning_rush',
    weather: 'clear',
    roadName: 'GST Road',
    landmark: 'Pallavaram Junction',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.9228,
    lng: 80.1439,
    severity: 3,
    description: 'Blind entry/exit near the railway station approach road; parked autos obscure visibility and force sudden stops.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Station Road',
    landmark: 'Tambaram Railway Station',
    verified: false
  },
  {
    type: 'accident',
    lat: 12.9631,
    lng: 80.1217,
    severity: 4,
    description: 'Crash-risk point where fast-moving traffic meets local turning vehicles and pedestrians at an unprotected crossing.',
    timeOfDay: 'evening_rush',
    weather: 'clear',
    roadName: 'Pallavaram-Thoraipakkam Road (SH109)',
    landmark: 'Near Pallavaram',
    verified: false
  },
  {
    type: 'sudden_brake',
    lat: 12.9005,
    lng: 80.1155,
    severity: 3,
    description: 'Abrupt braking near a curve and speed breakers; buses and vans stop suddenly to pick passengers.',
    timeOfDay: 'afternoon',
    weather: 'clear',
    roadName: 'Tambaram-Velachery Road',
    landmark: 'Selaiyur',
    verified: false
  },
  {
    type: 'blind_turn',
    lat: 12.8859,
    lng: 80.1036,
    severity: 4,
    description: 'Blind curve on Vandalur-Kelambakkam road with minimal lighting; heavy vehicles occupy full lane at night.',
    timeOfDay: 'night',
    weather: 'clear',
    roadName: 'Vandalur-Kelambakkam Road',
    landmark: 'Near Vandalur',
    verified: false
  }
];
